version: '3.9'

services:
  stackapidemo:
    image: ${DOCKER_REGISTRY-}stackapidemo
    build:
      context: .
      dockerfile: StackApiDemo/Dockerfile
  sql:
    image: "mcr.microsoft.com/mssql/server:latest"
    container_name: docker-sql-server-express
    ports:
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=MyPass@word
      - MSSQL_PID=Express